from selenium.webdriver.common.by import By

import time

class MonitorPage:

    def __init__(self, driver):
        self.driver = driver


    def testsearch1(self):
        driver = self.driver
        driver.find_element(By.XPATH, "//img[@alt='Monitor Icon']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//input[@class='PrivateSwitchBase-input css-1m9pwf3' and @type='checkbox']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//input[@class='PrivateSwitchBase-input css-1m9pwf3' and @type='checkbox']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='Links']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='Platform']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body1 css-9l3uo3']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='2h']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//button[text()='4h']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='12h']").click()
        time.sleep(4)
        driver.find_element(By.XPATH, "//button[text()='1d']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='1w']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='2w']").click()
        time.sleep(4)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)
        driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(2)
        driver.find_element(By.XPATH, "//a[text()='Platform']").click()
        time.sleep(1)
        driver.find_element(By.XPATH, "//button[text()='ASIC']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body1 css-9l3uo3']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='2h']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//button[text()='4h']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='12h']").click()
        time.sleep(4)
        driver.find_element(By.XPATH, "//button[text()='1d']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='1w']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='2w']").click()
        time.sleep(4)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(2)
        driver.find_element(By.XPATH, "//a[text()='ASIC']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//button[text()='BGP']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body1 css-9l3uo3']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//button[text()='2h']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//button[text()='4h']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='12h']").click()
        time.sleep(4)
        driver.find_element(By.XPATH, "//button[text()='1d']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='1w']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='2w']").click()
        time.sleep(4)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(2)
        driver.find_element(By.XPATH, "//a[text()='BGP']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//button[text()='Traffic']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//button[@class='MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeMedium css-1khtzrr']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//p[text()='Ethernet1']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='2h']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//button[text()='4h']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='12h']").click()
        time.sleep(4)
        driver.find_element(By.XPATH, "//button[text()='1d']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='1w']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[text()='2w']").click()
        time.sleep(4)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(2)